### ISSUE TITLE
NumberFormatException: For input string: "null"

### ISSUE THREAD

**Issue by marksarnold** [Baralga/baralga#21]
Hello,
getting the following exception on startup:
```
2016-12-29 15:07:52,962 ERROR [main] org.remast.baralga.gui.settings.UserSettings: For input string: "null"
java.lang.NumberFormatException: For input string: "null"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.valueOf(Long.java:803)
	at org.remast.baralga.gui.settings.UserSettings.doGetLong(UserSettings.java:554)
	at org.remast.baralga.gui.settings.UserSettings.getFilterSelectedProjectId(UserSettings.java:306)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:140)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
```
This is for the 1.8.0 portable version, downloaded yesterday.

Thank you.

**Comment by remast** [comment]
That's not a problem. Happens only the first time when the user settings are initialized. So it doesn't look nice in the log file but does not cause a problem. That's why this has very low priority for me.
