### ISSUE TITLE
Baralga Installer Fails on Newer Java

### ISSUE THREAD

**Issue by diamondq** [Baralga/baralga#44]
Attempted to run the 1.8.3 installer with AdoptOpenJDK 11

```
C:\temp>java -version
openjdk version "11.0.3" 2019-04-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.3+7)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.3+7, mixed mode)
```
and it generated an exception during the install:

```
C:\temp>java -jar c:\Users\xxx\Downloads\Baralga-Installer-1.8.3.jar
Command line arguments:
Cannot find named resource: 'packsLang.xml' AND 'packsLang.xml_eng'
WARNING: Failed to initialise shortcuts: Could not locate native library
====================
Installation started
Exception in thread "IzPack - Unpacker thread" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at com.izforge.izpack.installer.unpacker.UnpackerBase.logIntro(UnpackerBase.java:253)
        at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:285)
        at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:242)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

Worked fine when I forced it to use an older Oracle 1.8 that I had on my box.

**Comment by JimH44** [comment]
Same error with
```
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
```
My linux version is:
```
$ uname -a
Linux JimH15 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
It would be nice if the installer could check for this problem and work around it.
Thanks for this great program :-) I have used it on Windows successfully.

**Comment by JimH44** [comment]
I got past this error by choosing the other "English" that has a German flag beside it, but then the installer crashed with an error centred around:
`jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader`
I'll look for an issue about that.

**Comment by remast** [comment]
Please test again with v1.9.3 since I updated and fixed the installer.
