### ISSUE TITLE
Installer fails with cast error

### ISSUE THREAD

**Issue by JimH44** [Baralga/baralga#45]

**Comment by JimH44** [comment]
The Baralga installer fails with a casting error:
```
Installation started
Exception in thread "IzPack - Unpacker thread" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at com.izforge.izpack.installer.unpacker.UnpackerBase.logIntro(UnpackerBase.java:253)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:285)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:242)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
My version of java is:
``.
$ java -version
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Ubuntu-1ubuntu218.04.3, mixed mode, sharing)
...
My linux version is:

>  uname -a
> Linux JimH15 5.0.0-25-generic #26~18.04.1-Ubuntu SMP Thu Aug 1 13:51:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
>

**Comment by JimH44** [comment]
The same error with 1.8.1.

**Comment by JimH44** [comment]
1.8.0 installs nicely :-)
