### ISSUE TITLE
JCache API: Error loading default cache implementation, export 

### ISSUE THREAD

**Issue by annjulyleon** [Baralga/baralga#49]
**Problem:** Error while trying to export to iCal. Other export options work as intended. 
**OS:** Windows 10 Pro, TZ: Russian Standard Time/(UTC+03:00) Moscow, St. Petersburg, Volgograd), locale: ru-RU (1049)

**Error text:** `Error loading default cache implementation. Please ensure the JCache API dependency is included in the classpath, or override the cache implementation (e.g. via configuration: net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache)`

**Log**: 
`2020-03-20 07:33:42,036 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-03-20 07:33:42,170 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "D:\programs\Baralga-1.8.3\data".
2020-03-20 07:33:42,555 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-03-20 07:33:59,021 ERROR [SwingWorker-pool-3-thread-1] org.remast.baralga.gui.actions.AbstractExportAction: Error loading default cache implementation. Please ensure the JCache API dependency is included in the classpath, or override the cache implementation (e.g. via configuration: net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache)
java.lang.RuntimeException: Error loading default cache implementation. Please ensure the JCache API dependency is included in the classpath, or override the cache implementation (e.g. via configuration: net.fortuna.ical4j.timezone.cache.impl=net.fortuna.ical4j.util.MapTimeZoneCache)
	at net.fortuna.ical4j.model.TimeZoneLoader.lambda$cacheInit$1(TimeZoneLoader.java:285)
	at java.util.Optional.orElseGet(Unknown Source)
	at net.fortuna.ical4j.model.TimeZoneLoader.cacheInit(TimeZoneLoader.java:281)
	at net.fortuna.ical4j.model.TimeZoneLoader.<init>(TimeZoneLoader.java:85)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:125)
	at net.fortuna.ical4j.model.TimeZoneRegistryImpl.<init>(TimeZoneRegistryImpl.java:116)
	at net.fortuna.ical4j.model.DefaultTimeZoneRegistryFactory.createRegistry(DefaultTimeZoneRegistryFactory.java:48)
	at org.remast.baralga.model.export.ICalExporter.export(ICalExporter.java:45)
	at org.remast.baralga.gui.actions.AbstractExportAction$ExportWorker.doInBackground(AbstractExportAction.java:151)
	at org.remast.baralga.gui.actions.AbstractExportAction$ExportWorker.doInBackground(AbstractExportAction.java:111)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: javax/cache/configuration/Configuration
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.fortuna.ical4j.model.TimeZoneLoader.lambda$cacheInit$1(TimeZoneLoader.java:283)
	... 15 more
Caused by: java.lang.ClassNotFoundException: javax.cache.configuration.Configuration
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 18 more`

**Comment by remast** [comment]
Will be fixed in the upcoming version v1.8.4
