### ISSUE TITLE
Baralga portable stop working after latest windows 10 update 1903

### ISSUE THREAD

**Issue by akoka** [Baralga/baralga#53]
2020-06-15 10:58:48,193 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 10:58:48,325 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 10:58:48,619 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 10:58:48,724 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 10:58:55,031 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 10:58:55,095 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 10:58:55,288 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 10:58:55,366 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 10:59:12,026 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 10:59:12,089 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 10:59:12,282 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 10:59:12,359 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 11:00:08,098 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 11:00:08,160 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 11:00:08,352 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 11:00:08,431 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 11:00:26,183 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 11:00:26,248 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 11:00:26,440 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 11:00:26,520 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 11:00:37,542 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 11:00:37,604 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 11:00:37,794 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 11:00:37,873 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)
2020-06-15 11:01:54,077 INFO  [main] org.remast.baralga.gui.BaralgaMain: Starting Baralga version 1.8.3.
2020-06-15 11:01:54,145 INFO  [main] org.remast.baralga.gui.BaralgaMain: Using application data directory "C:\Users\Corrado\4Portable\PortableApps\Baralga\data".
2020-06-15 11:01:54,338 INFO  [main] org.remast.baralga.model.BaralgaDAO: Using Baralga DB Version: 1, description: Initial database setup..
2020-06-15 11:01:54,418 ERROR [main] org.remast.baralga.gui.BaralgaMain: 
java.lang.NullPointerException
	at org.remast.baralga.model.BaralgaDAO.addActivity(BaralgaDAO.java:294)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:440)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:402)
	at org.remast.baralga.gui.model.PresentationModel.stop(PresentationModel.java:393)
	at org.remast.baralga.gui.model.PresentationModel.initialize(PresentationModel.java:153)
	at org.remast.baralga.gui.BaralgaMain.initModel(BaralgaMain.java:324)
	at org.remast.baralga.gui.BaralgaMain.main(BaralgaMain.java:106)

**Comment by remast** [comment]
Should be fixed in v1.9.3 otherwise please reopen.
